ballot/urls.py
from django.urls import path
from . import views

app_name = 'ballot'
urlpatterns = [
    path('create/', views.create, name='create'),
    path('seal/', views.seal, name='seal'),
]

bbevoting_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('ballot/', include('ballot.urls')),
    path('sim/', include('simulation.urls')),
    path('', include('welcome.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

simulation/urls.py
from django.urls import path
from . import views

app_name = 'simulation'
urlpatterns = [
    path('generate/', views.generate, name='generate'),
    path('seal/', views.seal, name='seal'),
    path('transactions/', views.transactions, name='transactions'),
    path('blockchain/', views.blockchain, name='blockchain'),

    path('block/<str:block_hash>/', views.block_detail, name='block_detail'),

    path('verify/', views.verify, name='verify'),
    path('sync/', views.sync, name='sync'),
    path('sync_block/<int:block_id>/', views.sync_block, name='sync_block'),
]

welcome/urls.py
from django.urls import path
from . import views

app_name = 'welcome'
urlpatterns = [
    path('home/', views.home, name='home'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('clear_data/', views.clear_data, name='clear_data'),
    # path('user_login/', views.user_login, name='user_login'),
]

welcome/models.py
from django.db import models

# Create your models here.

welcome/views.py
import subprocess

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core import mail
from django.http import HttpResponse
from django.shortcuts import render, redirect
from Crypto.PublicKey import ECC
from django.template.loader import render_to_string
from django.utils.html import strip_tags

from bbevoting_project.settings import SEND_EMAIL
from simulation.models import *
import os


@login_required(login_url='/')
def home(request):
    context = {
        'tx': settings.N_TRANSACTIONS,
        'bl': settings.N_BLOCKS,
    }
    return render(request, 'welcome/home.html', context)


def sign_up(request):
    if request.method == "POST":
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        password = request.POST.get('password')
        user_obj = User.objects.create(first_name=first_name, last_name=last_name, username=email, email=email)
        user_obj.set_password(password)
        # user_obj.save(co)

        # user_details_obj = User.objects.create(user=user_obj)

        # Generate Private key
        name = "{}_{}".format(user_obj.first_name, user_obj.last_name)
        key = ECC.generate(curve='P-256')
        private_key = key.export_key(format='PEM')

        f = open('utils/private_' + name + '.pem', 'wt')
        f.write(key.export_key(format='PEM'))
        f.close()

        print('**********************')
        print(private_key)
        print('**********************')

        # Generate Public Key

        f = open('utils/public_' + name + '.pem', 'wt')
        f.write(key.public_key().export_key(format='PEM'))
        f.close()

        user_obj.public_key = key.public_key().export_key(format='PEM')
        user_obj.save()

        if SEND_EMAIL:
            try:
                subject = 'Welcome to E Voting System'
                html_message = render_to_string('welcome/private_key.html',
                                                {'username': user_obj.email, "private_key": private_key})
                plain_message = strip_tags(html_message)
                from_email = settings.EMAIL_HOST_USER

                to = user_obj.email

                mail.send_mail(subject, plain_message, from_email, [to], html_message=html_message)
            except Exception as e:
                messages.warning(request, 'Invalid Email!')
        messages.success(request, 'User Sign Up success..!')
        return redirect('/')

    elif request.method == "GET":
        return render(request, 'welcome/sign_up.html')


def user_login(request):
    if request.method == "POST":
        username = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/home')
        else:
            messages.warning(request, "Invalid login")
            return render(request, 'welcome/login.html')
    elif request.method == "GET":
        if request.user.is_authenticated:
            return redirect('/home')
        return render(request, 'welcome/login.html')


@login_required(login_url='/')
def user_logout(request):
    logout(request)
    return redirect('/')


from django.db import connection


@login_required(login_url='/')
def clear_data(request):
    Vote.objects.all().delete()
    VoteBackup.objects.all().delete()
    Block.objects.all().delete()

    cursor = connection.cursor()
    cursor.execute('ALTER TABLE simulation_vote AUTO_INCREMENT = 1')
    cursor.execute('ALTER TABLE simulation_votebackup AUTO_INCREMENT = 1')
    cursor.execute('ALTER TABLE simulation_block AUTO_INCREMENT = 1')
    cursor.fetchall()
    cursor.close()
    return redirect('welcome:home')

welcome/templates/welcome/home.html
{% extends 'base.html' %}
{% load static %}
{% block title_bl %}Home{% endblock %}

{% block body_bl %}
    <div class="container">
        <div>
            <div style="text-align: center;">
                {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
            {#            <p style="text-align: center;"><img src="{% static 'ballot/img/logo.png' %}"></p>#}
            <h1 style="padding-top:4%;padding-bottom:3%; text-align: center">Blockchain Voting</h1>

        </div>
        <div class="row">
            <div class="col-md-5 menu">
                <h2>"BLOCK"</h2>
                <p>This part will show:</p>
                <ul>
                    <li>Example of ballot</li>
                    <li>Ballot structure</li>
                    <li>Signature verification</li>
                    <li>Block sealing process</li>
                </ul>
                <div class="btn-menu">
                    <a class="btn btn-outline-primary btn-block btn-menu" href="{% url 'ballot:create' %}"
                       role="button">Start</a>
                </div>
            </div>
            <div class="col-md-5 menu">
                <h2>"CHAIN"</h2>
                <p>This part will show:</p>
                <ul>
                    <li>Batch transactions</li>
                    <li>Block chaining</li>
                    <li>Block detail</li>
                    <li>Blocks verification</li>
                </ul>
                <div class="btn-menu">
                    <a class="btn btn-link btn-menu" href="{% url 'simulation:transactions' %}" role="button">See
                        transactions</a>
                    <a class="btn btn-link btn-menu" href="{% url 'simulation:blockchain' %}" role="button">See
                        blocks</a>
                    <a class="btn btn-link btn-menu" href="{% url 'welcome:clear_data' %}" role="button">Clear Data</a>
                    {#                    <a class="btn btn-outline-primary btn-menu" href="{% url 'simulation:generate' %}" role="button">Start</a>#}

                </div>
            </div>
        </div>
    </div>
{% endblock %}

welcome/templates/welcome/login.html
{% load static %}
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Blockchain Voting</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/main.css' %}"/>
    <script src="{% static 'js/main.js' %}"></script>
</head>
{% block body_bl %}
    <div class="container">
        <div>
{#            {% if messages %}#}
{#                {% for message in messages %}#}
{#                    <div class="alert alert-success" id="success-alert">#}
{#                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span#}
{#                                aria-hidden="true">&times;</span>#}
{#                        </button>#}
{#                        {{ message|escape }}#}
{#                    </div>#}
{#                {% endfor %}#}
{#            {% endif %}#}
            <p style="text-align: center;"><img src="{% static 'ballot/img/logo.png' %}"></p>
            <h1 style="padding-bottom:5%; text-align: center">Blockchain Voting Log In</h1>

        </div>
        <form action="{% url 'welcome:user_login' %}" method="POST">
            {% csrf_token %}

            <div class="form-group" style="margin-left: 29%">
                <div class="row col-md-12">
                    <label for="voter-id-input" class="col-md-3">Email:</label>
                    <input name="email" type="text" class="form-control col-md-4" id="first_name"
                           placeholder="Email" autofocus>
                </div>
                <br>
                <div class="row col-md-12">
                    <label for="voter-id-input" class="col-md-3">Password:</label>
                    <input name="password" type="password" class="form-control col-md-4" id="last_name"
                           placeholder="Password" autofocus>
                </div>
                <br>
            </div>

            <button type="submit" style="width: 25%; margin-left: 38%" class="btn btn-primary btn-block">Log in
            </button>
        </form>
        <a style="margin-left: 32%;" href="{% url 'welcome:sign_up' %}">Don't having Login Credentials, click here to
            register yourself.</a>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>

{#    <script type="text/javascript">#}
{#        $(document).ready(function () {#}
{#            window.setTimeout(function () {#}
{#                $("#success-alert").fadeTo(500, 0).slideUp(500, function () {#}
{#                    $(this).remove();#}
{#                });#}
{#            }, 4000);#}
{#        })#}
{#    </script>#}
{% endblock %}

welcome/templates/welcome/private_key.html
<html>
<head>
</head>
<body>
Dear {{ username }},
<br>
<br>
Greetings !!!
<br>
<br>
You have sign up successfully in e voting.
<br>
Your Private Key is as below,
<br>
Please note, this key will required for voting.
without key you are not able to vote.

<br>
<br>
Private Key:
<br>
{{ private_key }}
<br>
<br>
<br>

Best Regards,
<br>
<br>
E Voting system,
<br>
<br>
</body>
</html>

welcome/templates/welcome/sign_up.html
{% load static %}
{#{% block title_bl %}Sign Up{% endblock %}#}
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Blockchain Voting</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"/>
    <link rel="stylesheet" href="{% static 'css/main.css' %}"/>
    <script src="{% static 'js/main.js' %}"></script>
</head>
{% block body_bl %}
    <div class="container">
        <div>
            <p style="text-align: center;"><img src="{% static 'ballot/img/logo.png' %}"></p>
            <h1 style="padding-bottom:5%; text-align: center">Blockchain Voting Sign Up</h1>
        </div>
        <form action="{% url 'welcome:sign_up' %}" method="POST">
            {% csrf_token %}

            <div class="form-group" style="margin-left: 29%">
                <div class="row col-md-12">
                    <label for="voter-id-input" class="col-md-3">First Name:</label>
                    <input name="first_name" type="text" class="form-control col-md-4" id="first_name"
                           placeholder="Enter First name" autofocus required>
                </div>
                <br>
                <div class="row col-md-12">
                    <label for="voter-id-input" class="col-md-3">Last Name:</label>
                    <input name="last_name" type="text" class="form-control col-md-4" id="last_name"
                           placeholder="Enter Last name" autofocus required>
                </div>
                <br>
                <div class="row col-md-12">
                    <label for="voter-id-input" class="col-md-3">Email:</label>
                    <input name="email" type="email" class="form-control col-md-4" id="email"
                           placeholder="Enter Email" autofocus required>
                </div>
                <br>
                <div class="row col-md-12">
                    <label for="voter-id-input" class="col-md-3">Password:</label>
                    <input name="password" type="password" class="form-control col-md-4" id="password"
                           placeholder="Enter Password" autofocus required>
                </div>
                <br>
                <div class="row col-md-12">
                    <label for="voter-id-input" class="col-md-3">Confirm Password:</label>
                    <input name="cfm_password" type="password" class="form-control col-md-4" id="cfm_password"
                           placeholder="Confirm Password" autofocus required>
                </div>
            </div>
            <button type="submit" style="width: 25%; margin-left: 36%" class="btn btn-primary" id="submit">Sign Up
            </button> &nbsp;&nbsp;&nbsp;<a href="{% url 'welcome:user_login' %}">Log In</a>
        </form>
    </div>

{#    <script type="text/javascript">#}
{#        $(document).ready(function () {#}
{#            $("#submit").click(function () {#}
{#                alert('**')#}
{#                return false;#}
{#            })#}
{#        })#}
{#    </script>#}
{% endblock %}