ballot/urls.py
from django.urls import path
from . import views

app_name = 'ballot'
urlpatterns = [
    path('create/', views.create, name='create'),
    path('seal/', views.seal, name='seal'),
]

bbevoting_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('ballot/', include('ballot.urls')),
    path('sim/', include('simulation.urls')),
    path('', include('welcome.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

welcome/urls.py
from django.urls import path
from . import views

app_name = 'welcome'
urlpatterns = [
    path('home/', views.home, name='home'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('clear_data/', views.clear_data, name='clear_data'),
    # path('user_login/', views.user_login, name='user_login'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Sim: {% block title_bl %}Blockchain Voting{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"/>
    <link rel="stylesheet" href="{% static 'css/main.css' %}"/>
    <script src="{% static 'js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark" id="nav-bar">
    <a class="navbar-brand" href="/home/"><img style="max-width: 70px;margin: -20%;"
                                               src="{% static 'ballot/img/logo.png' %}"> </a>

    <!-- Links -->
    <ul class="navbar-nav pull-right">
        <li class="nav-item">
            <a class="nav-link" href="/home/">Home</a>
        </li>
    </ul>
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <a class="nav-link" href="javascript:void(0)">{{ name }}</a>
            </li>
            <li class="nav-item active">
                {#                <a class="nav-link" data-toggle="modal" data-target="#myModal" href="#">Log Out</a>#}
                {#                <a class="nav-link" href="{% url 'welcome:user_logout' %}" data-toggle="modal" data-target="#myModal">Logout</a>#}
                <a class="nav-link" href="#" data-toggle="modal" data-target="#myModal">Logout</a>
            </li>
        </ul>
    </div>
</nav>


{# Delete Modal#}
<div class="modal" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Log Out Confirm</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                Are you sure want to Logout?
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                <a href="{% url 'welcome:user_logout' %}">
                    <button type="button" class="btn btn-danger" id="log-out">Log Out</button>
                </a>
            </div>

        </div>
    </div>
</div>
{# #}

{% block body_bl %}
{% endblock %}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

</body>
</html>